language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make test_xunit
after_success:
  - make docker_build
  - PASSWORD=$DOCKER_PASSWOD make docker_push
deploy:
  provider: heroku
  app: fathomless-lowlands-30515
  api_key: $Heroku_key
